# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_likelihood_C <- function(model_num_topics, model_alpha, doc_dlength, model_logProbW, doc_words, doc_counts, phi, var_gamma) {
    .Call(`_pLDA_compute_likelihood_C`, model_num_topics, model_alpha, doc_dlength, model_logProbW, doc_words, doc_counts, phi, var_gamma)
}

compute_beta_involved_likelihood_C <- function(model_num_topics, doc_dlength, model_logProbW, doc_words, doc_counts, phi) {
    .Call(`_pLDA_compute_beta_involved_likelihood_C`, model_num_topics, doc_dlength, model_logProbW, doc_words, doc_counts, phi)
}

updateMat <- function(x) {
    invisible(.Call(`_pLDA_updateMat`, x))
}

log_sum_C <- function(a, b) {
    .Call(`_pLDA_log_sum_C`, a, b)
}

do_e_step_C <- function(doc_length, oldphi, nTopics, phi, digamma_gam, model_logProbW, docs_words, gammav, docs_counts) {
    invisible(.Call(`_pLDA_do_e_step_C`, doc_length, oldphi, nTopics, phi, digamma_gam, model_logProbW, docs_words, gammav, docs_counts))
}

do_m_step_C <- function(doc_length, nTopics, docs_counts, phi, docs_words, sstats_classword, sstats_classtotal) {
    invisible(.Call(`_pLDA_do_m_step_C`, doc_length, nTopics, docs_counts, phi, docs_words, sstats_classword, sstats_classtotal))
}

mstep_beta_C <- function(model_ntopics, model_nterms, sstats_classword, model_logProbW, sstats_classtotal) {
    invisible(.Call(`_pLDA_mstep_beta_C`, model_ntopics, model_nterms, sstats_classword, model_logProbW, sstats_classtotal))
}

